project: 
  name: MeinProjekt 
  language: php 
  framework: laravel 
  style: strict 
  architecture: 
    - domain-driven
    - modular
    - cqrs
    - SOLID
coding:
  php_version: "8.5"
  strict_types: true
  formatting: pint
  static_analysis: phpstan
  test_framework: pest
rules:
  forbidden:
    - global functions
    - static state
    - facades
    - direct database access
  allowed:
    - dependency injection
    - value objects
    - DTOs
structure:
  domain: app/Domain
  application: app/Application
  infrastructure: app/Infrastructure
  ui: app/UI
  documentation: docs
  tests: tests
tests:
  framework: pest
  naming: "*Test.php"
  coverage_required: true
  mutation_testing: pest
  test_types:
    - unit
    - integration
    - functional
    - acceptance
    - architecture
docs:
  format: markdown
  generate_readme: true
  generate_architecture_diagrams: true
  include_code_examples: true
agent:
  verbosity: high
  reasoning: deep
  refactor_safely: true
  ask_before_large_changes: true
  generate_commits: false
  cli: wsl
repository:
  type: git
  remote: origin
  default_branch: main
  protected_branches:
    - main
    - develop
  commit_style: conventional-commits