project:
  name: ResumeHaven
  language: php
  framework: pimcore, symfony
  style: strict
  architecture:
    - bundles
    - SOLID
coding:
  php_version: "8.4"
  strict_types: true
  static_analysis: phpstan
rules:
  forbidden:
    - global functions
    - static state
    - direct database access
  allowed:
    - dependency injection
    - value objects
    - DTOs
structure:
  application: app
  pimcore: pimcore
  documentation: docs
  tests: tests
tests:
  naming: "*Test.php"
  coverage_required: true
  test_types:
    - unit
    - integration
    - functional
    - acceptance
    - architecture
docs:
  format: markdown
  generate_readme: true
  generate_architecture_diagrams: true
  include_code_examples: true
agent:
  verbosity: high
  reasoning: deep
  refactor_safely: true
  ask_before_large_changes: true
  generate_commits: false
  terminal: wsl
