{
 "title": "PHP-FPM",
 "description": "PHP-FPM monitoring dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(phpfpm_accepted_connections_total, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Process Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_processes_total{namespace=~\"^$Namespace$\",state=\"active\"}) by (namespace,pod)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Max Children Reached",
   "type": "graph",
   "description": "Number of times the process limit has been reached",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_max_children_reached_total{namespace=~\"^$Namespace$\"}) by (namespace,pod)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Idle Process Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_processes_total{namespace=~\"^$Namespace$\",state=\"idle\"}) by (namespace,pod)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Active Max Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_active_max_processes{namespace=~\"^$Namespace$\"}) by (namespace,pod)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Listen Queue Max Connections",
   "type": "graph",
   "description": "Max number of connections the listen queue has reached since FPM start",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue_max_connections{namespace=~\"^$Namespace$\"}) by (namespace,pod)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Listen Queue Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_listen_queue_connections{namespace=~\"^$Namespace$\"}) by (namespace,pod)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "graph",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_slow_requests_total{namespace=~\"^$Namespace$\"}) by (namespace,pod)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Listen Queue Length Connections",
   "type": "graph",
   "description": "The length of the socket queue, dictating maximum number of pending connections",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_listen_queue_length_connections{namespace=~\"^$Namespace$\"}) by (namespace,pod)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "graph",
   "description": "Total number of accepted connections",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_accepted_connections_total{namespace=~\"^$Namespace$\"}) by (namespace,pod)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  }
 ]
}